spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 122222222
            clientSecret: <github-client-secret>

taco:
  orders:
    pageSize: 10

logging:
  level:
    tacos: DEBUG

---
spring:
  profiles: prod

logging:
  level:
    tacos: WARN