### Find all Content
GET http://localhost:8080/api/content

### Get Content by id
GET http://localhost:8080/api/content

### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
    "id": 2,
    "title": "My Second Blog Post",
    "desc": "My second blog post",
    "status": "IDEA",
    "contentType": "ARTICLE",
    "dateCreated": "2023-10-31T21:42:08.5242633",
    "dateUpdated": null,
    "url": ""
}